# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: example
    ports:
        - 5432:5432

  app:
    build: ./app
    restart: always
    ports:
        - 3000:3000
        - 8002:8002
    volumes:
        - ./app:/usr/server/app
        - nodemodules:/usr/server/app/node_modules
        - dotprisma:/usr/server/app/node_modules/.prisma
        - atprisma:/usr/server/app/node_modules/@prisma
    links:
        - db
    depends_on: 
        - db

volumes:
    nodemodules: {}
    dotprisma: {}
    atprisma: {}